spring:
  application:
    name: chat

  datasource:
    url: jdbc:postgresql://localhost:5432/AI_CHAT_DB
    username: postgres
    password: sanathkumar

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

gemini:
  api-key: AIzaSyCyz3hUErOnef4U9_LGBZr3fsJUjIfzQsM
  model: gemini-2.5-flash-lite
  base-url: https://generativelanguage.googleapis.com/v1beta/models

groq:
  api-key: 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
  base-url: https://api.groq.com/openai/v1
  model: llama-3.1-8b-instant

logging:
  level:
    org:
      springframework:
        security: DEBUG



